config/routes.rb
AwesomeAnswers::Application.routes.draw do

resources :questions

end

app/models/question.rb
class Question < ActiveRecord::Base



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

def index
#by default will just render the index.html.erb file
	@questions = Question.all
end

def new
	@question = Question.new
end

def create
	Rails.logger.info params[:question]
	question = Question.new params.require(:question).permit([:title, :body])
	question.save

	redirect_to questions_path

end

def show
	@question = Question.find(params[:id])

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = "container">

<%= yield %>
</div>
</body>
</html>

app/views/questions/index.html.erb
<h1>Welcome to Awesome Answers</h1>

<%= link_to "New Question", new_question_path, class: "btn btn-primary"%>

<% @questions.each do |question| %>
	
	<!-- <p><%= question.title.capitalize %></p> -->
	<p><%= link_to question.title.upcase, question %></p> 
	<p><%= question.body.truncate(200) %></p>
	<hr>
<% end %>
	

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
<div class="form-group">
<%= f.label :title, "My Title Modified" %>
<%= f.text_field :title, class: "form-control" %>
</div>

<br>
<div class="form-group">
<%= f.label :body %>
<%= f.text_area :body, class: "form-control" %>
</div>
<br>

<%= f.submit "Save this Question", class: "btn btn-primary" %>



<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>	
<br>

<%= link_to "All Questions", questions_path %>